
name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Build with Maven
        run: mvn clean verify
        working-directory: Spring-Boot-Assignment

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            # -Dsonar.organization=pavithrachandran70
            # -Dsonar.projectKey=pavithrachandran70_Assignment
            # -Dsonar.java.binaries=Spring-Boot-Assignment/bookservice/target/classes,Spring-Boot-Assignment/libraryservice/target/classes
            # -Dsonar.coverage.jacoco.xmlReportPaths=Spring-Boot-Assignment/bookservice/target/site/jacoco/jacoco.xml,Spring-Boot-Assignment/libraryservice/target/site/jacoco/jacoco.xml
            # -Dsonar.exclusions=**/target/**,**/jacoco-resources/**,**/prettify.js,**/*.min.js
            # -Dsonar.javascript.exclusions=**/prettify.js
            # -Dsonar.coverage.exclusions=**/Librarian.java
              -Dsonar.organization=pavithrachandran70
              -Dsonar.projectKey=pavithrachandran70_Assignment
              -Dsonar.sources=bookservice/src/main/java,libraryservice/src/main/java
              -Dsonar.tests=bookservice/src/test/java,libraryservice/src/test/java
              -Dsonar.java.binaries=bookservice/target/classes,libraryservice/target/classes
              -Dsonar.coverage.jacoco.xmlReportPaths=bookservice/target/site/jacoco/jacoco.xml,libraryservice/target/site/jacoco/jacoco.xml
              -Dsonar.exclusions=**/Librarian.java,**/target/**,**/jacoco-resources/**,**/prettify.js,**/*.min.js
              -Dsonar.javascript.exclusions=**/prettify.js
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKENS }}



   

